### ISSUE TITLE
where is the dataset?

### ISSUE THREAD

**Issue by hfut-mhz** [DeepLearnXMU/mc_tit#2]
Could you please provide the url for the dataset?

**Comment by Nonoor** [comment]
We are currently in the process of organizing the dataset, and we plan to release it within this month. Once it is ready, we will provide the URL for you to access the dataset.  Thank you for your inquiry, please stay tuned for further updates.

**Comment by dididadaren** [comment]
hello，where is the dataset

**Comment by jwy-sss** [comment]
We have released the dataset in the ocrmt30k_data folder
