### ISSUE TITLE
The data  has some problem in downloading

### ISSUE THREAD

**Issue by dididadaren** [DeepLearnXMU/mc_tit#4]
I just  download  3g  data  when  the  downloading stopped  many times.
So ,I believe  this  is  a  problem.
![image](https://github.com/DeepLearnXMU/mc_tit/assets/73410744/4edda107-9004-4398-ab05-b5852bc7131f)

**Comment by jwy-sss** [comment]
Thank you for bringing this issue to our attention. We have identified an alternative download channel for the dataset, and you can get it after filling out the Google form.
