### ISSUE TITLE
wmt22 and icdar2019_lvst_week data is not found

### ISSUE THREAD

**Issue by madajie9** [DeepLearnXMU/mc_tit#6]
Hello, I tried run fiarseq-preprocess-pretrain.sh and there is an error:
![image](https://github.com/DeepLearnXMU/mc_tit/assets/49145147/d830b128-3fc4-4dae-9855-e7034392e62a)
data/wmt22_zh_en_bpe is needed but could not be found
(in official website https://www.statmt.org/wmt22/translation-task.html, i could download dataset but the format is not same with yours)

besides that,  in stage 3, data/icdar19_lsvt_weak  is needed but I cound not find it
 (in official website, https://rrc.cvc.uab.es/?ch=16&com=downloads for weak data, there is only a json label file)

Could you please provide the download for these 2 dataset used in your training?

Thank you very much!

**Comment by zhasx0v0** [comment]
hello,could you please help me with the wmt22 dataset:in official website https://www.statmt.org/wmt22/translation-task.html,  which dataset did you choose?
Thank you very much!

**Comment by madajie9** [comment]
thanks to the author' guide by email, here is the solution:

1. To prepare the 'data/wmt22_zh_en_bpe' dataset, you will need to tokenize (mosesdecoder toolkit) and apply BPE (Byte-Pair Encoding) to the original dataset. We have provided the BPE file at the following link: 

https://github.com/DeepLearnXMU/mc_tit/blob/main/ocrmt30k_data/bpe/zhen.bpe

2. For the data in the link (https://rrc.cvc.uab.es/?ch=16&com=downloads). You need to register and log in to your account on that website, just try again.
